services:
  - type: web
    name: villa-gianni-pms
    runtime: node
    plan: free
    buildCommand: npm install --production=false && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_r1fvxIDGLNA8@ep-empty-smoke-ahhjh27q-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: VITE_DATABASE_URL
        value: postgresql://neondb_owner:npg_r1fvxIDGLNA8@ep-empty-smoke-ahhjh27q-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require
      - key: NODE_VERSION
        value: 20.11.0
      - key: ELECTRON_SKIP_BINARY_DOWNLOAD
        value: "1"
